version: 1.0.{build}
configuration:
  - Release
before_build:
  - nuget restore
build:
  parallel: true
  project: WoWEditor6.sln
  verbosity: quiet
after_build:
  - 7z a Neo.zip %APPVEYOR_BUILD_FOLDER%\WDBXEditor\WDBXEditor\bin\Release
artifacts:
  - path: WDBXEditor.zip
    name: WDBXEditor
